# MySQL.  Versions 4.1 and 5.0 are recommended.
# 
# Install the MYSQL driver
#   gem install mysql2P
#
# Ensure the MySQL gem is defined in your Gemfile
#   gem 'mysql2'
#
# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html
base: &base
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  username: root
  password: kenrome001
  host: 127.0.0.1
  port: 3306

development:
  <<: *base
  database: baoxian028

test:
  <<: *base
  database: baoxian028

production:
  <<: *base
  database: baoxian028
############################
remote: &remote
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  username: root
  password: kenrome001
  host: localhost
  port: 3303
#for exporter
common_development:
  <<: *remote
  database: baoxian028

local_development:
  <<: *base
  database: insurance_forager